### ISSUE TITLE
Notification Event [3sp]

### ISSUE THREAD

**Issue by edanfesi** [platzily/email-consumer#13]
- subscribe to the notification queue 
- send the event to the respective queue (Email, slack)
- Create the event in the State Machine (DB)

Acceptance Criteria
- Connection to Rabbit
- Connection with the State Machine
- PR

**Comment by EnriqueePerez** [comment]
I am closing this Issue because it doesn't belong in this. This requirement is from [dealer](https://github.com/platzily/dealer). I could transfer the issue but I decided to create a new one with the new templates in order to make it more understandable to everyone. You can find the new issue [here](https://github.com/platzily/dealer/issues/7)
